- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   
- name: install pip3
  apt: name=python3-pip state=present 
  
- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose
      
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ image }}"
    username: "{{ username }}"
    password: "{{ password }}"
    reauthorize: yes
    
- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8069:8069
    state: started
 
